### ISSUE TITLE
Create struct from JSON fed into the `stdin`

### ISSUE THREAD

**Issue by NightMachinery** [galeone/rts#2]
E.g.,
```
echo '  {
    "Book Id": 30558257,
    "Title": "Unsouled (Cradle, #1)",
    "Author": "Will Wight",
    "Author l-f": "Wight, Will",
    "Additional Authors": "",
    "ISBN": "=\"\"",
    "ISBN13": "=\"\"",
    "My Rating": 0,
    "Average Rating": 4.18,
    "Publisher": "Hidden Gnome Publishing",
    "Binding": "Kindle Edition",
    "Number of Pages": 294,
    "Year Published": 2016,
    "Original Publication Year": 2016,
    "Date Read": "",
    "Date Added": "2020/10/11",
    "Bookshelves": "xianxia, fiction, 87p",
    "Bookshelves with positions": "xianxia (#1), fiction (#13), 87p (#27)",
    "Exclusive Shelf": "87p",
    "My Review": "",
    "Spoiler": "",
    "Private Notes": "",
    "Read Count": 0,
    "Recommended For": "",
    "Recommended By": "",
    "Owned Copies": 0,
    "Original Purchase Date": "",
    "Original Purchase Location": "",
    "Condition": "",
    "Condition Description": "",
    "BCID": ""
  }' | rts
```

It would be awesome if it generated the parser/reader code, too.

**Comment by galeone** [comment]
Why not, that's a nice feature request!

Are you a Go developer? If yes, and you have some spare time, perhaps you can open a pull request with your attempt :smile: 

If you don't anticipate me instead, I'll implement this feature as soon as I find some free slot (crazy busy with several side projects - but I should be able to work on this sometime)

**Comment by NightMachinery** [comment]
You know, just after opening this FR, it came to me that this should already exist. I opened Google, and the results looked promising, but I am busy atm, so I just bookmarked the search. 

I myself could also write this, but not in `Go`. :) This is fine, there is no reason the code generator should use the same language as its target. Funny thing is, I wanted the whole JSON parser to generate yet another file ...

**Comment by galeone** [comment]
@NightMachinary I found some time to work on this eventually. I covered your exact scenario - even if some time is passed I hope you can still use `rts` and find it useful :smile:

**Comment by NightMachinery** [comment]
[**@galeone**](https://github.com/galeone) commented on [Sep 26, 2021, 12:03 PM GMT+3:30](https://github.com/galeone/rts/issues/2#issuecomment-927259759 "2021-09-26T08:33:46Z - Replied by Github Reply Comments"):
> [@NightMachinary](https://github.com/NightMachinary) I found some time to work on this eventually. I covered your exact scenario - even if some time is passed I hope you can still use `rts` and find it useful 😄

Thanks, I am sure it will come in handy in the future. I finished that old project using manual code "generation." :D
